// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0LcsK3YQseWKFfo39EpxmAgqSsFQAIg8',
    appId: '1:104904426270:web:0a17d514b3f91354cfbf0f',
    messagingSenderId: '104904426270',
    projectId: 'handwave-connect',
    authDomain: 'handwave-connect.firebaseapp.com',
    storageBucket: 'handwave-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1LpcZEtayKUsq1-cicWa0WnYzhAJ6KU',
    appId: '1:104904426270:android:a7086c6ea9719701cfbf0f',
    messagingSenderId: '104904426270',
    projectId: 'handwave-connect',
    storageBucket: 'handwave-connect.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0LcsK3YQseWKFfo39EpxmAgqSsFQAIg8',
    appId: '1:104904426270:web:e5b5ff73783e394fcfbf0f',
    messagingSenderId: '104904426270',
    projectId: 'handwave-connect',
    authDomain: 'handwave-connect.firebaseapp.com',
    storageBucket: 'handwave-connect.firebasestorage.app',
  );
}
